### ISSUE TITLE
TypeError: e.getLanguage(...) is undefined

### ISSUE THREAD

**Issue by Qeole** [isagalaev/highlight.js#1235] opened 2016-07-02 17:08 UTC
Hi there,
I am having an issue with version 9.5.0. When trying to highlight code on a page with the `hljs.initHighlightingOnLoad()` function, I get an error, and for most of languages, the detection fails (details further down).

## How to reproduce

I use the following HTML page:

``` .html
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style type="text/css">code{white-space: pre;}</style>
    <link rel="stylesheet" href="styles/arduino-light.css">
    <script src="highlight.pack.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
  </head>
  <body>
    <h1 id="test">Test</h1>
    <pre><code class="vhdl" id="foo">
/*
 * Update preferences
 */
spref.on("", onPrefChange);
function onPrefChange(aPref) {
  switch (aPref) {
    case "invert":
      setIcons();
      button.icon = gIconInit;
      break;
    default:
      break;
  }
}
    </code></pre>
  </body>
</html>
```

and I open this page in my browser. Alternatively, I could reproduce the issue by using this snippet at the end of the body instead of calling the `hljs.initHighlightingOnLoad()` function:

``` .html
    <script>
    let block = document.getElementById("foo");
    hljs.highlightBlock(block);
    </script>
```

## What happens

Syntax highlighting is performed, but:
  * For **most** languages, it does not respect the languages I indicate in the `class` attribute (here, `vhdl`). I do not know whether it picks a “default” language, or automatically performs auto-detection.
  * For **some** languages, such as Lisp, the detection does happen correctly. I do not know why some languages work better than the others in this context.
  * For **all** languages, whether the detection occurs correctly or not, the browser Javascript console logs the following error message:

        TypeError: e.getLanguage(...) is undefined

## Versions

* This issue occurs with version 9.5.0.
* It does not occur with version 9.4.0.
* I could build but did not manage to find how to include the library I obtained from the master branch of the Git repo, so I do not know if it occurs with the current HEAD.

In case it matters, my browser is Firefox v48.0a2.

**Comment by pkaminski** [comment] 2016-07-16 22:14
I believe the last error (`e.getLanguage(...) is undefined`) is due to the language definitions not being ordered properly in the minified file.  The `arduino` and `sqf` languages are derived from `cpp`, but come first in the file; moving them to the end fixes the exception.

**Comment by isagalaev** [comment] 2016-08-09 04:02
This looks like a dupe of #1220. I suspect all the mis-detection problems are due to the broken package.

**Comment by isagalaev** [comment] 2016-08-09 05:30
I've fixed the ordering issue in downloads, so this should be fixed too. Please re-download the package and check how it works. Don't hesitate to reopen the issue if it doesn't!

(Also, the version of highlight.js itself doesn't matter, the fix was in the download code on the site.)

**Closed by isagalaev** 2016-08-09 05:30 UTC
Labels: bug

**Comment by Qeole** [comment] 2016-08-09 19:31
Thanks @isagalaev! I confirm the issue is fixed and the detection works just fine again. Sorry for the duplicate…
