### ISSUE TITLE
Work in simulator not work in iPhone device

### ISSUE THREAD

**Issue by zixun** [isagalaev/highlight.js#922] opened 2015-09-03 18:03 UTC
dont know why

**Comment by isagalaev** [comment] 2015-09-03 18:16
It's impossible to do anything from this description. Please do some investigation to show what is exactly wrong with highlight.js here.

**Comment by Sannis** [comment] 2015-09-03 22:54
Looks like a duplicate of #891. My apologises, but we need help from experienced mobile web developers to investigate this.

**Comment by zixun** [comment] 2015-09-04 07:08
@Sannis  @isagalaev  i wrote a demo for this [TestHighLight](https://github.com/zixun/TestHighLight), highlight.js is work in simulator not work in iPhone device, please use Xcode7-Bete6,it can use device testing without Certificate。please inform me If there is any research results。 I'm using highlight.js and my application is about to go online. thank you~

**Comment by isagalaev** [comment] 2015-09-05 02:03
@zixun what you're proposing is that some of use should get a Mac, set it up, buy or license a particular development environment, learn it, learn how to build your project, get an iPhone, figure out how to upload your app to it… and then try to guess how exactly you were expecting highlight.js to work and what does it mean that it doesn't. All that to find a problem that most probably has nothing to do with highlight.js itself, as you say it works fine in an emulator.

In other words, you're in a much better position to investigate it. It looks like the iPhone either can't find the script at the path you provide or may be your app doesn't have permissions for it or something like that in an environment.

**Closed by isagalaev** 2015-09-05 02:03 UTC
Labels: bug

**Comment by isagalaev** [comment] 2015-09-05 02:09
btw, quickly looking through your code revealed at least one possible reason: you're misspeled "arta.css" with a capital letter here: https://github.com/zixun/TestHighLight/blob/master/html/test.html#L12

**Comment by zixun** [comment] 2015-09-05 09:04
@isagalaev  I'm so sorry,it's my fault！highlight.js works well at device while change to 'arta.css'. Thx
