### ISSUE TITLE
Crash on page load with bower and highlight.pack.js

### ISSUE THREAD

**Issue by Soullivaneuh** [isagalaev/highlight.js#765] opened 2015-02-26 13:50 UTC
Here, the example: http://jsfiddle.net/soullivaneuh/yobmx5t0/

When I used the `highlight.pack.js` gave by bower on `8.4` version or `master`, my browser get stuck on page load with 100% CPU usage.

I don't have any problem if I load my page with your cdn link (`//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/highlight.min.js`).

I don't know what, but I think you have something wrong on your bower package! ;)

**Comment by isagalaev** [comment] 2015-02-26 23:08
First of all, we don't maintain the bower package, so I can't tell for sure what's happening there. However, what you see is most probably a regex-related bug in Less highlighting that was causing such behavior lately. You don't see it in the CDN version as it simply doesn't contain that language. The bug is fixed in master and I can't reproduce it with the master code on your snippet. If you're still seeing it with the *master* code from bower it might be due to it being in fact something older…

**Comment by Soullivaneuh** [comment] 2015-02-27 11:35
Hmm and who is maintaining bower package ?

It would be very useful and less painful to have your own bower package as bower is used by many developers, isn't it ? :)

**Comment by isagalaev** [comment] 2015-02-27 15:43
It certainly will be *more* painful as it would be another thing to maintain. There are quite a few packaging solutions in JavaScript world right now and we encourage anyone interested to support their favorite tool themselves.

**Comment by Soullivaneuh** [comment] 2015-03-02 09:44
Hmm in case of bower, it's juste a bower.json file! ;)

Anyway, I suppose the package is here: https://github.com/components/highlightjs ?

Will open a issue on it, thanks for your help.

**Comment by Sannis** [comment] 2015-03-02 10:07
Yep, that's it.

**Closed by Sannis** 2015-03-02 10:07 UTC
