### ISSUE TITLE
Very hight CPU consumption and long processing time

### ISSUE THREAD

**Issue by slorber** [isagalaev/highlight.js#701] opened 2015-01-07 18:35 UTC
Hi

Using `highlightBlock` with default settings, my UI gets frozen on some content.

Here's a sample of the outerHTML of these elements for reproduction:

```
<pre>SampleRemoteServiceAsync instance <span>=</span> <span>(</span>SampleRemoteServiceAsync<span>)</span> GWT
                    .<span>create</span><span>(</span>SampleRemoteService.<span>class</span><span>)</span><span>;</span>
ServiceDefTarget target <span>=</span> <span>(</span>ServiceDefTarget<span>)</span> instance<span>;</span>
target.<span>setServiceEntryPoint</span><span>(</span>GWT.<span>getModuleBaseURL</span><span>(</span><span>)</span> <span>+</span> SERVICE_URI<span>)</span><span>;</span></pre>
```

```
<pre>&nbsp;
<span>if</span><span>(</span><span>!</span><span>Context</span>.<span>getInstance</span><span>(</span><span>)</span>.<span>isOffline</span><span>(</span><span>)</span><span>)</span><span>{</span>
      SampleRemoteServiceAsync instance <span>=</span> <span>(</span>SampleRemoteServiceAsync<span>)</span> GWT     .<span>create</span><span>(</span>SampleRemoteService.<span>class</span><span>)</span><span>;</span>
      ServiceDefTarget target <span>=</span> <span>(</span>ServiceDefTarget<span>)</span> instance<span>;</span>
      target.<span>setServiceEntryPoint</span><span>(</span>GWT.<span>getModuleBaseURL</span><span>(</span><span>)</span> <span>+</span> SERVICE_URI<span>)</span><span>;</span>
&nbsp;
      <span>return</span> instance<span>;</span>
<span>}</span> <span>else</span> <span>{</span>
      <span>return</span> <span>new</span> OfflineSampleService<span>(</span><span>)</span><span>;</span>
<span>}</span></pre>
```

Both takes about 5 second to highlight. On the output I can see some HighlightJS tags.
During that time there's a high CPU consumption and my UI is completely frozen.

So it makes this plugin unusable for me :(
Any idea?

**Comment by slorber** [comment] 2015-01-08 11:51
Hmmm I tried to isolate this problem in a jsfiddle sandbox but it seems Highlight works fine.
Actually the problem is not the content itself.


I am using ReactJS and it seems this long highlight problem happens when the DOM node I'm trying to highlight has no parentNode. Maybe it could be nice to investigate in Highlight why this takes a long time in this specific case (can't we highlight a detached DOM node?), or at least issue a warning to help users to know the source of the problem.

I'll investigate a little more and try to understand why ReactJS give me nodes with no parent (I didn't expect that, and otherwise nodes have parents!)

**Comment by slorber** [comment] 2015-01-08 14:12
After debugging, I could not find anything to help you.

It seems related to LESS, as when stopping the main thread during freeze time I always see LESS parser in action.

I tried to reproduce in a JSFiddle sandbox and I could not with the same HTML markup: http://jsfiddle.net/2e27xz33/

I checked this issue and reverted from 8.4 to 8.1, and now it works fine:
https://github.com/isagalaev/highlight.js/issues/666

So it seems to me a regression

**Comment by slorber** [comment] 2015-01-08 14:36
@isagalaev I tried to backport your fix of https://github.com/isagalaev/highlight.js/issues/666 locally in version 8.4.0.

The code does not freeze anymore, but the highlight is incorrect. The highlight of the samples above worked much better with version 8.1.0 for me

**Comment by isagalaev** [comment] 2015-02-03 23:12
If highlighting seems broken compared to a few versions ago it's probably due to mis-detection of some newly added language. I'll have a look!

**Comment by arve0** [comment] 2015-02-24 11:30
I'm experiencing the same. `highlightAuto(code)` will be stuck in an endless loop when trying [`highlight('less', code, false)`](https://github.com/isagalaev/highlight.js/blob/master/src/highlight.js#L487). Here is some code to reproduce:

```js
var hljs = require('highlight.js');

var code = "        når jeg mottar [Sted: Hønefoss v]\
        gå til x: (6) y: (-112)\
        sett [Reis til v] til [Hønefoss]\
        vent til (berører [Helikopter v]?)\
        send melding [Fant sted v] og vent\
        send melding [Sted: Tromsø v]\
\
        når jeg mottar [Sted: Tromsø v]\
        gå til x: (103) y: (121)\
        sett [Reis til v] til [Tromsø]\
        vent til (berører [Helikopter v]?)\
        send melding [Fant sted v] og vent\
        send melding [Sted: Lillehammer v]\
\
        når jeg mottar [Sted: Lillehammer v]\
        gå til x: (14) y: (-94)\
        sett [Reis til v] til [Lillehammer]\
        vent til (berører [Helikopter v]?)\
        send melding [Fant sted v] og vent\
        send melding [Sted: Bergen v]\
\
        når jeg mottar [Sted: Bergen v]\
        gå til x: (-52) y: (-107)\
        sett [Reis til v] til [Bergen]\
        vent til (berører [Helikopter v]?)\
        send melding [Fant sted v] og vent\
        send melding [Sted: Narvik v]\
\
        når jeg mottar [Sted: Narvik v]\
        gå til x: (91) y: (90)\
        sett [Reis til v] til [Narvik]\
        vent til (berører [Helikopter v]?)\
        send melding [Fant sted v] og vent\
        send melding [Avslutt v]";

result = hljs.highlight('less', code, false);
console.log(result);
```

**Comment by arve0** [comment] 2015-02-24 11:40
To be specific, this is where it stops: https://github.com/isagalaev/highlight.js/blob/master/src/highlight.js#L434 (unable to step into with debugger)

**Comment by isagalaev** [comment] 2015-02-24 17:33
A few of bugs in Less definition were fixed lately in master and will be available with the next release. Could you test that with the master build?

**Comment by arve0** [comment] 2015-02-24 17:38
Sure, 2 sec.

**Comment by arve0** [comment] 2015-02-24 17:49
No problem with master.

**Comment by isagalaev** [comment] 2015-02-24 17:50
OK. Closing this issue then. Thanks for checking!

**Closed by isagalaev** 2015-02-24 17:50 UTC
Labels: bug
