### ISSUE TITLE
Error when parse PHP sublanguage in HTML lang 

### ISSUE THREAD

**Issue by doiftrue** [isagalaev/highlight.js#1007] opened 2015-11-30 08:04 UTC
Here is screen that all explain http://c2n.me/3r23J4K

**Comment by Sannis** [comment] 2015-11-30 21:11
Th screenshot is a good thing, but minimal code example is always good to be here so we shouldn't take to many yo dig into WP code to find it. Is this screenshot is from https://core.trac.wordpress.org/browser/trunk/src/wp-includes/taxonomy.php? It is highlighted with other tool, probably pygments. With highlight.js master is looks good except highlighted meta in comments:
![screen shot 2015-12-01 at 00 10 51](https://cloud.githubusercontent.com/assets/77367/11484613/04fcaf4c-97c0-11e5-931b-5623e4bcf19e.png)

**Comment by doiftrue** [comment] 2015-12-01 19:38
Here is the original code on my site http://wp-kama.ru/code?file_path=/wp-includes/taxonomy.php#L178

**Comment by Sannis** [comment] 2015-12-02 20:37
Can you try 9.0? It does not breaks here for me.

**Comment by Sannis** [comment] 2015-12-02 21:52
![screen shot 2015-12-03 at 00 50 36](https://cloud.githubusercontent.com/assets/77367/11545336/e69bc76a-9957-11e5-9845-4c5240295f97.png)

@isagalaev what do you think about `<?php` in comments? We can try to fix this in language definition, but I think it is quicker to do this in styles.

**Comment by isagalaev** [comment] 2015-12-02 22:09
As far as I can see, fixing this in the language definition is the right thing to do and is done simple by removing this: https://github.com/isagalaev/highlight.js/blob/master/src/languages/php.js#L54 (I didn't investigate why it was there in the first place).

Masking it in all styles isn't gonna work as we can't rely on every author of every new style to include a special rule to mask something that is simply a bug in the language definition.

**Comment by doiftrue** [comment] 2015-12-03 05:26
I found the problem reason, but how fix it i don't know it seems not simple. It's not because of PREPROCESSOR inside comment - that is correct!

Broblem is in `xml/html` brush, because it has PHP sublanguage. The code ( http://wp-kama.ru/code?file_path=/wp-includes/taxonomy.php ) hightlights as `html`. It start at the begining as PHP sublang and ends incorrectly at the point of the error.

For example, let's try hightlight such code as HTML:

```
<?php
echo 'foo';

/*
<?php echo 'foo'; ?>
*/

echo 'foo';
?>

<div class="bar">foo</div>
<a href="http://foo">foo</a>
```

I get this:
![](http://clip2net.com/clip/m399748/685b2-clip-13kb.png?nocache=1)

**Comment by Sannis** [comment] 2015-12-14 21:12
IMO this is quite rare example that is not respectively simple to fix. In such case it is better to specify code language via HTML class depending on code file extension. @isagalaev what do you think?

**Comment by isagalaev** [comment] 2015-12-15 21:01
It may well be that my original idea of how PHP works was wrong. We have a test looking like this:

```html
<? echo 'php'; /* ?>
<p>some html</p>
<? end of comment */ ?>
```

It assumes that the first `?>` breaks the PHP part in the middle of the comment, falls out into plain HTML and then the next `<?` resumes the PHP comment again. But now I'm having doubts about it: may be a comment is a comment, and PHP doesn't break on preprocessor brackets inside it. 

Could you guys look what it actually does? I'm pretty far away from PHP, so I don't even know where to start setting up the environment to test it. And I couldn't find any decent online playground tool…

**Comment by landzup** [comment] 2016-01-01 01:04
Here's how PHP closing tags works in multiline and inline comments.
* multiline comments: the PHP closing tag contained is just comment, it is not parsed as a token;
* inline comments: the PHP closing tag ends the comment token and is parsed as token.

To be clearer I attach an image of the correctly highlighted test code proposed by Ivan:

![php-closing-tag-inside-multiline-comment-test_20160101](https://cloud.githubusercontent.com/assets/3382599/12069349/a0368e88-b02a-11e5-8d60-058c867637ee.png)

I tested the code snippet on an Apache 2.0 server over Linux with PHP 5.6 setting the maximum error reporting level.

**Comment by isagalaev** [comment] 2016-01-20 00:30
Just as a status update: I'm still thinking how to solve it best. We now have another language (unmerged MaskJS) that may benefit from different rules on how we treat sub-languages in various situations.

**Comment by isagalaev** [comment] 2016-01-20 00:32
@landzup btw, do I understand it right that in 

    <?php echo 'php'; // comment ?>

the last `?>` is not part of the comment and closes the fragment?

**Comment by doiftrue** [comment] 2016-01-20 06:41
> the last ?> is not part of the comment and closes the fragment?

NO, it is part of comment! Any symbol after // or in /**/ is part of comment in PHP

**Comment by isagalaev** [comment] 2016-01-20 07:06
Okay. I asked because you said:

> inline comments: the PHP closing tag ends the comment token and is parsed as a token.

And I felt it's strange that two kinds of comments are different in this regard. Or did I misunderstand?

**Comment by landzup** [comment] 2016-01-20 12:27
Hello to everybody,
and thanks for giving attention to my issue notification, but I think it
has not been understood.

@doiftrue: I am telling just the opposite thing. In PHP, the inline comment
DOES NOT ignore the closing tag.

By tokenizing a PHP document, the closing tag "?>" is parsed as T_CLOSE_TAG
even if inside an inline comment.
It is the expected behaviour, it is part of the specs and it works this way
on each PHP version I tested.

I hope I was clear enough, and that you will not ignore my words.

Have a nice day.









2016-01-20 8:06 GMT+01:00 Ivan Sagalaev <notifications@github.com>:

> Okay. I asked because you said:
>
> inline comments: the PHP closing tag ends the comment token and is parsed
> as a token.
>
> And I felt it's strange that two kinds of comments are different in this
> regard. Or did I misunderstand?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/isagalaev/highlight.js/issues/1007#issuecomment-173113100>
> .
>



-- 
Cordiali Saluti / Kind Regards / Cordialement / Mit freundlichen Grüßen /
Saludos Cordiales
Emanuele del Grande

**Comment by doiftrue** [comment] 2016-01-20 19:19
Oh, sorry, sorry, it was my mistake... 

@landzup you are absolutely right: closing `?>` tag works with inline comment `//` or `#`, but not work with block comments `/**/`

**Comment by landzup** [comment] 2016-01-22 11:50
Exactly, it is right :)

Thanks!


2016-01-20 20:19 GMT+01:00 doiftrue <notifications@github.com>:

> Oh, sorry, sorry, it was my mistake...
>
> @landzup <https://github.com/landzup> you are absolutely right: closing ?>
> tag works with inline comment // or #, but not work with block comments
> /**/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/isagalaev/highlight.js/issues/1007#issuecomment-173330155>
> .
>



-- 
Cordiali Saluti / Kind Regards / Cordialement / Mit freundlichen Grüßen /
Saludos Cordiales
Emanuele del Grande

**Comment by isagalaev** [comment] 2016-02-01 17:35
So, does this look right?
![php-xml-2](https://cloud.githubusercontent.com/assets/99931/12725327/0bdb74a0-c8c7-11e5-8d46-ed2352922e11.png)

**Comment by landzup** [comment] 2016-02-01 22:04
Yes, that's correct.

2016-02-01 18:35 GMT+01:00 Ivan Sagalaev <notifications@github.com>:

> So, does this look right?
> [image: php-xml-2]
> <https://cloud.githubusercontent.com/assets/99931/12725327/0bdb74a0-c8c7-11e5-8d46-ed2352922e11.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/isagalaev/highlight.js/issues/1007#issuecomment-178087994>
> .
>



-- 
Cordiali Saluti / Kind Regards / Cordialement / Mit freundlichen Grüßen /
Saludos Cordiales
Emanuele del Grande

**Closed** 2016-02-02 06:14 UTC
Labels: bug

**Comment by isagalaev** [comment] 2016-02-02 06:15
So this should work now, please check!

**Comment by doiftrue** [comment] 2016-02-03 21:33
No, is's not work correctly. I update highlight.js to last version 9.1 and xml, php langs. And test next two code on each lang.

example 1

```
<?php
echo 'foo';
function(){}

/*
<?php echo 'foo'; ?>
*/

echo 'foo';
?>

<div class="bar">foo</div>
<a href="http://foo">foo</a>
```

example 2

```
<p>text</p>
<?php echo 'string'; // inline comment ?>
<?php echo 'string'; /* long ?> comment */ ?>
<p>text</p>
```

both of them must have the same colors, because PHP could have HTML as sublang and HTML could have PHP as sublang. But it's not work on any lang correctly

#### What we have now?

If PHP lang is set:

All comments are correct now, but HTML part are broken (but it's not work in old version too). In some cases we can say PHP lang is OK!

![](http://savepic.net/7699966.png)

If XML (HTML) lang is set:
Both has errors:
![](http://savepic.net/7682558.png)

**Comment by isagalaev** [comment] 2016-02-03 21:44
> I update highlight.js to last version 9.1

9.1 was released a month ago, and the fix just landed in master, so you have to get the code and [build it][] to test it. Also note that there's now a separate language "php-xml" that highlights a mixture of the two.

[build it]: http://highlightjs.readthedocs.org/en/latest/building-testing.html

**Comment by doiftrue** [comment] 2016-02-03 21:58
I take this code
https://github.com/isagalaev/highlight.js/blob/master/src/highlight.js
just some hours ago. Is it last one?

**Comment by isagalaev** [comment] 2016-02-03 22:23
Yeah, that's the master, it should work. But make sure you include "php-xml" in the build. Or just build with all of them.

**Comment by doiftrue** [comment] 2016-02-03 22:28
Sorry I dont use bilder, and use lans separatelly. Now I see php-html.js new file.

Add it and WOW it is works!!!

![](http://savepic.net/7699952.png)

**Comment by doiftrue** [comment] 2016-02-03 22:37
If it possible maybe better separate xml and html langs? I mean remove HTML alias from xml lang and rename PHP-XML lang to HTML itself?

But for now my problem is soleved, thanks a lot!!!

**Comment by isagalaev** [comment] 2016-02-05 06:21
The namings aren't final, it's still work in progress.
