### ISSUE TITLE
A confusing piece of code.

### ISSUE THREAD

**Issue by Satyam** [isagalaev/highlight.js#1168] opened 2016-05-08 22:00 UTC
In the following piece of code, it incorrectly identified the slash in the template string containing the `</ul>` as the start of a regular expression (see the third line counting from the bottom).

Source:

```js
axios.get(`/data/v1/projects/${window.location.search.substr(1)}`)
  .then((response) => {
    const prj = response.data;
    document.getElementById('contents').innerHTML =
      `<h1>${prj.name}</h1><p>${prj.descr}</p><ul>${
        Object.keys(prj.tasks).map((tid) => {
          const task = prj.tasks[tid];
          return `<li><input type="checkbox" ${
            task.completed ? 'checked' : ''
          } /> &nbsp; ${task.descr}</li>`;
        }).join('\n')
      }</ul>`;
    document.title = `Project ${prj.pid}: ${prj.name}`;
  });
```

Highlighted output:

```html
<pre><code class="language-js hljs javascript">axios.get(<span class="hljs-string">`/data/v1/projects/<span class="hljs-subst">${window.location.search.substr(1)}</span>`</span>)
  .then((response) =&gt; {
    <span class="hljs-keyword">const</span> prj = response.data;
    <span class="hljs-built_in">document</span>.getElementById(<span class="hljs-string">'contents'</span>).innerHTML =
      <span class="hljs-string">`&lt;h1&gt;<span class="hljs-subst">${prj.name}</span>&lt;/h1&gt;&lt;p&gt;<span class="hljs-subst">${prj.descr}</span>&lt;/p&gt;&lt;ul&gt;<span class="hljs-subst">${
        Object.keys(prj.tasks).map((tid) =&gt; {
          const task = prj.tasks[tid];
          return `&lt;li&gt;&lt;input type="checkbox" ${
            task.completed ? 'checked' : ''
          }</span> /&gt; &amp;nbsp; <span class="hljs-subst">${task.descr}</span>&lt;/li&gt;`</span>;
        }).join(<span class="hljs-string">'\n'</span>)
      }&lt;<span class="hljs-regexp">/ul&gt;`;
    document.title = `Project ${prj.pid}: ${prj.name}`;
  });</span></code></pre>
```

**Comment by Satyam** [comment] 2016-05-09 13:41
Found the problem elsewhere and the common thing is having a template string embedded in another one, like this:

```js
`before ${` inner before ${1} inner after`} after`
```

Funny thing is that you can see it properly highlighted in this message, but hljs seems to get confused.  The issue is not about confusing the slash as the start of a regular expression, the problem comes from before that.   I guess this is as simple an example as I can make.

**Comment by isagalaev** [comment] 2016-05-09 17:37
Yes, the problem is that we currently handle `${ .. }` substitutions very simplistically: we don't expect any structure within and break on the first closing `}`. I'll fix the breakage but supporting the whole of JavaScript within template strings would take more time.

**Closed** 2016-09-21 05:09 UTC
Labels: bug
