### ISSUE TITLE
Incorrect Scala highlighting

### ISSUE THREAD

**Issue by prurph** [isagalaev/highlight.js#930] opened 2015-09-12 13:19 UTC
This affects most themes and seems to be because there is no `hljs-params` scope or the like defined. Here is an example from the demo on the main site:

![highlight js demo 2015-09-12 09-06-40](https://cloud.githubusercontent.com/assets/6109531/9831705/56510638-592f-11e5-8737-7982eca1c2cd.png)

**Comment by Sannis** [comment] 2015-09-12 14:42
@prurph I can reproduce this only when using `:common` set of languages, in this case this fragment recognised as Ruby. But we do not have Scala example on site. How are you get this?

![screen shot 2015-09-12 at 17 40 18](https://cloud.githubusercontent.com/assets/77367/9831992/6360cb38-5975-11e5-9816-99036b846de9.png)

Maybe this is caused by

**Comment by Sannis** [comment] 2015-09-12 14:45
Site live demo also loo
![screen shot 2015-09-12 at 17 44 54](https://cloud.githubusercontent.com/assets/77367/9832006/0a81fdec-5976-11e5-8272-1ae4386669c0.png)
ks good at this moment:

**Comment by prurph** [comment] 2015-09-12 14:46
I was talking about the live demo you just linked. In that screenshot the colors are actually showing the same issue--note how the `:` after things and the first paren after `spindle` are blue.

**Comment by Sannis** [comment] 2015-09-12 14:57
My bad(

**Comment by isagalaev** [comment] 2015-09-12 15:02
Yeah, the problem is definitely there but it seems to be fixed in the new-styles branch which is an overhaul of class names and styles across all the languages: #348. And it's actually nearing completion!

**Comment by Sannis** [comment] 2015-09-12 15:08
Also current language definition looks strange - in this fragment `type T;` is class, `val things: Seq[T]` is function.

**Comment by isagalaev** [comment] 2015-09-12 15:33
I demoted `val` from starting a function, so `things` in the example is no longer a title. I will also close the issue as the params mis-highlighting is fixed in the new-styles branch.

Thanks for reporting this!

**Closed by isagalaev** 2015-09-12 15:33 UTC
Labels: bug

**Comment by prurph** [comment] 2015-09-12 20:54
Awesome! Thank you!
