### ISSUE TITLE
Highlight es6 module syntax

### ISSUE THREAD

**Issue by Alxandr** [isagalaev/highlight.js#756] opened 2015-02-22 07:45 UTC
ES6 uses `import`, `export` and `from` as keywords in module syntax. See sample usages here: http://www.2ality.com/2014/09/es6-modules-final.html

**Comment by isagalaev** [comment] 2015-02-22 08:33
Could you make a pull request with a fix for that? Shouldn't be anything more than adding new keywords to the list.

**Comment by Alxandr** [comment] 2015-02-22 08:44
`from` is a valid variable name though. It's easy enough to add the keywords, but there should be a difference between

```javascript
import {foo} from 'bar';
```

and

```javascript
const from = foo;
```

**Comment by Alxandr** [comment] 2015-02-22 09:06
The same is valid for `as`.

```javascript
import { foo as bar } from 'baz'
```

I don't know how to implement features like that in highlight.js

**Comment by isagalaev** [comment] 2015-02-22 17:26
Yes, that's a whole another story then. It's possible and we'll get to it as time allows. Thanks for clarification!

**Comment by Alxandr** [comment] 2015-02-22 19:05
For now though, I can add `import` and `export` as keywords (which is what it seems most do to get off easy).

**Comment by Terri5732** [comment] 2015-02-23 15:00
Ok thank you so much I appreciate you guys like you wouldn't believe!  I'm not as tech savvy as I'm a bit older and didn't grow up in this tech generation so I'm learning on my own.  But I'm a fast learner and good problem solver.  You guys blow me away with your IQ's this is so foreign it's like trying to learn another language like Farci at 4+ 🔫🍸🍸🍸🎓

**Comment by Sannis** [comment] 2015-02-23 17:20
@isagalaev, should we add import mode with highlighted `as` keyword or can just close this issue?

**Comment by Alxandr** [comment] 2015-02-23 18:03
@Sannis I'd say `from` is more important than `as` (as `from` almost always occurs in import statements).

**Comment by isagalaev** [comment] 2015-02-23 18:27
@Sannis yeah, it should be a proper mode starting with `import` and ending with either a semicolon or the end of the line and having `from` and `as` as keywords. No idea when I could get to it so if you could pick it up that'd be awesome :-). But no closing yet, certainly :-)

**Comment by Terri5732** [comment] 2015-02-23 22:59
No problem , no rush take your time I'm not picky either.

**Closed** 2015-02-28 11:34 UTC

**Comment by Sannis** [comment] 2015-02-28 11:36
Added!

@isagalaev, I also found that we need duplicate `beginKeywords` in `keywords` property if second one exists in mode definition. Should we fix it?

**Comment by isagalaev** [comment] 2015-03-04 00:35
I remember we even talked about it earlier and decided to leave it as is for now as it allows redefining beginKeywords completely at the price of having to repeat them in a few cases. Not a big deal either way I think :-)

**Comment by keepitreal** [comment] 2016-02-07 15:51
I've noticed that fat arrow syntax (lambda) function parameters don't receive the `hljs-params` class like they do with ES5 lambdas.

**Comment by isagalaev** [comment] 2016-02-07 16:23
@keepitreal looks like we don't highlight `=>` functions in JavaScript at all (and never have, so it's not a regression). Do you think you might be able to take it on and make a pull request? It may be non-trivial, but we have a [similar feature in coffeescript.js][1] that can be copied over and modified, if needed.

P.S. It's usually not a good idea to comment on a closed issue as it may fall out of view pretty easily.

[1]: https://github.com/isagalaev/highlight.js/blob/master/src/languages/coffeescript.js#L105-L123

**Comment by keepitreal** [comment] 2016-02-07 19:54
@isagalaev Good point. I'll open a pull request.

**Comment by paladox** [comment] 2019-02-08 23:44
@keepitreal any progress on your pull request? I cannot find one for the es6 `=>`.
