### ISSUE TITLE
Question: unable to build, not valid JS file output?

### ISSUE THREAD

**Issue by ZitRos** [isagalaev/highlight.js#974] opened 2015-11-04 21:52 UTC
Hello developers!

Excuse me for probably strange question, but how to build the project <b>correctly</b>?

After <code>npm install</code>, I ran <code>node --harmony tools/build.js -t browser</code> as it was said in developer docs and get:
```
Starting build.
Copying documentation.
Writing documentation.
Generating demo.
Building highlight.js pack file.
Compressing highlight.js pack file.
Writing highlight.js pack file.
Finished build.
```
It looks OK, but from <code>tools/developer.html</code>, when trying to include the built script I see the next JavaScript error:
```
Uncaught ReferenceError: hljs is not defined
```
This is obviously correct for the JavaScript interpreter to throw this error, because output <code>highlight.pack.js</code> file starts from the next:
```
/*! -- comment -- */
hljs.registerLanguage("1c", function(e){...
```
Could you please clarify or explain, how <code>hljs</code> have to appear there? How to build the project in a right way to get a solid, not broken file?

Thank you!

**Comment by isagalaev** [comment] 2015-11-04 22:08
I just did a fresh checkout and `npm install` and the build does work for me fine. I didn't use the `--harmony` switch though. What might be the source of the problem is that we have recently switched to node 4.x in master. Which version of node are you using?

**Comment by ZitRos** [comment] 2015-11-05 13:43
On my Win 10 x64 machine I cloned the repository again and tried this for:
+ node v0.12.* with --harmony flag
+ node v5
+ node v4.2.2

All of this didn't help for <code>node tools/build.js -t browser</code>.

The build/highlight.pack.js file is still beginning from
```js
/*! highlight.js v8.9.1 | BSD3 License | git.io/hljslicense */
hljs.registerLanguage("1c",function(e){var t=
```

Is it possible this issue to be OS-related?

**Comment by ZitRos** [comment] 2015-11-08 14:02
@isagalaev, confirmed this issue is OS-related. I am unable to build non-broken library under Windows, when running build on Ubuntu worked well. Any ideas?

**Comment by Sannis** [comment] 2015-11-08 19:59
Can you share hljs builded under Windows with us? We can try to compare it with Ubuntu one.

**Comment by ZitRos** [comment] 2015-11-09 17:22
Of course! Here is the result of <code>node tools/build.js -t browser</code> on my Windows machine: [zip](https://mega.nz/#!Go03haiB!0nDNbP70ey2QFvPEyhK_yT7AnUa3cvZc9gDQuVSy0Xs).
Thank you!

**Comment by VoldemarLeGrand** [comment] 2015-11-14 20:32
The issue seems to be in build scripts: [`tasks.js`](https://github.com/isagalaev/highlight.js/blob/3c12521bba4ce7614cab2dd0793a91b3a425e42d/tools/tasks.js#L234) uses `\n\n` regex to split `highlight.js` and inject language definitions right before the last part. Split does not work in Windows checkout as expected. As result build script places all language definitions in the very beginning of the `highlight.pack.js`, well before the `hljs` variable definition. Resulting `highlight.pack.js` looks like this :

    /*! highlight.js v8.9.1 | BSD3 License | git.io/hljslicense */
    hljs.registerLanguage(...);
    hljs.registerLanguage(...);

    (function(factory) {
      // Setup highlight.js for different environments. First is Node.js or
      // CommonJS.
    ...
      hljs.UNDERSCORE_TITLE_MODE = {
        className: 'title',
        begin: hljs.UNDERSCORE_IDENT_RE,
        relevance: 0
      };

      return hljs;
    }));

I ran into this problem Friday night and I made a patch to use system specific EOL anywhere in build scripts: VoldemarLeGrand/highlight.js@d6f5b91dd9811b79f4dd92b02c5b288deb7124dd

But now I think a better solution would be to force Git always checkout Unix version of all JavaScript files in project: VoldemarLeGrand/highlight.js@7aaba1f4d6a926997a0c258c436eb1f6305006e9 as it is already done for test files in [`test/.gitattributes`](https://github.com/isagalaev/highlight.js/blob/3c12521bba4ce7614cab2dd0793a91b3a425e42d/test/.gitattributes). This solution seems to be consistent with current [`.editorconfig`](https://github.com/isagalaev/highlight.js/blob/3c12521bba4ce7614cab2dd0793a91b3a425e42d/.editorconfig#L1-L2) settings.

**Comment by ZitRos** [comment] 2015-11-15 11:23
@VoldemarLeGrand, thank you so much! Unix-style line endings solution worked for me.

I think you should make a pull request with your changes. All the code should be OS-independent, or at least <code>.gitattributes</code> should appear in repository master branch to make the right setup for every user.

**Comment by VoldemarLeGrand** [comment] 2015-11-15 15:39
Build tool of the project - the nodejs code in `tools` - is OS-independent. But it has some [never explicitly declared] requirements on the data it process, i.e. input file structure with injection point marker (actually this marker - the last `\n\n` sequence - got corrupted while Git checkout on Windows). Tricky part is that the input/output data for build tool is JavaScript code... which should be OS-independent as we have stated :)

@ZitRos, you are right, the build should be system independent. However, the proper method to achieve this goal  - coding conventions or "sophisticated" build tool - is up to authors to choose. They have both of my proposals,.. and they have a better position to choose one.

**Comment by isagalaev** [comment] 2015-11-17 19:49
@VoldemarLeGrand thanks for the investigation!

I've merged the solution with .gitattributes as it's consistent with what we did before and clarified a comment in the file.

**Closed by isagalaev** 2015-11-17 19:49 UTC
Labels: code
